# Generated by Django 3.0.5 on 2020-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardimtalepler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardimlar',
            name='aciklama',
            field=models.TextField(verbose_name='Yardım Açıklaması'),
        ),
        migrations.AlterField(
            model_name='yardimlar',
            name='baslik',
            field=models.CharField(max_length=100, verbose_name='Yardım Başlığı'),
        ),
    ]
