# Generated by Django 3.0.5 on 2020-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardimtalepler', '0002_auto_20200502_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardimlar',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
