# Generated by Django 3.0.5 on 2020-05-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardimtalepler', '0003_auto_20200502_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='yardimlar',
            name='adres',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='yardimlar',
            name='telefon',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
