# Generated by Django 3.0.5 on 2020-05-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardimtalepler', '0005_yardimlar_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='yardimlar',
            name='u_firstname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yardimlar',
            name='u_lastname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
